# Generated by Django 4.2.4 on 2023-09-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file_saving_model",
            name="myfile",
            field=models.FileField(upload_to="the_app/static/uploaded_files/"),
        ),
    ]
